# Generated by Django 2.0.2 on 2018-07-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_auto_20180702_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTRiskAssessment',
            fields=[
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assessment.Application')),
                ('termsconditions_URL', models.URLField(help_text='Please copy and paste the apps terms and conditions from the vendors website. Make sure you get the T&Cs for the version of the app you want.')),
                ('privacypolicy_URL', models.URLField(help_text='Please copy and paste the apps privacy policy from the vendors website. Make sure you get the privacy policy for the version of the app you want.')),
                ('dhb_record_volume', models.CharField(choices=[('TENS', '10s'), ('HUNDREDS', '100s'), ('THOUSANDS', '1,000s'), ('TENTHOUSANDS', '10,000s'), ('HUNDREDTHOUSANDS', '100,000s')], default='TENS', help_text='Provide an estimate of the number of records we expect to store in the application on an annual basis.', max_length=15)),
                ('dhb_downtime_before_critical', models.CharField(choices=[('H', 'Hours'), ('D', 'Days'), ('M', 'Months'), ('I', 'Indefinitely')], default='H', help_text='We can be without this app before our service can no longer function properly. Specify the time interval.', max_length=1)),
                ('dhb_log_data_changes', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='We will be able to notice if someone accidentally or maliously alters our data stored in the cloud service.', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='cloudictbriefcloudriskassessment',
            name='app',
        ),
        migrations.DeleteModel(
            name='CloudICTBriefCloudRiskAssessment',
        ),
    ]
