# Generated by Django 2.0.2 on 2018-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_application_assess_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='owner_decision',
            field=models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('S', 'Assessing')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='application',
            name='privacy_comments',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='privacy_decision',
            field=models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('S', 'Assessing')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='application',
            name='security_comments',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='security_decision',
            field=models.CharField(choices=[('A', 'Accept'), ('R', 'Reject'), ('S', 'Assessing')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='informationclassification',
            name='special_handling_sensitive_other',
            field=models.CharField(help_text='Other', max_length=200, null=True),
        ),
    ]
