# Generated by Django 2.0.2 on 2018-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_auto_20180702_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationclassification',
            name='special_handling_sensitive_other',
            field=models.CharField(blank=True, help_text='Other', max_length=200, null=True),
        ),
    ]
