# Generated by Django 2.0.2 on 2018-07-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20180703_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ictriskassessment',
            name='dhb_breach_plan',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='We have a plan we can put into effect if we learn that there has been a privacy or security breach concerning our data stored in the cloud service.', max_length=1),
        ),
        migrations.AddField(
            model_name='ictriskassessment',
            name='dhb_disrupt_plan',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='We have a plan we can put into effect if the cloud service is disrupted for an extended period.', max_length=1),
        ),
        migrations.AddField(
            model_name='ictriskassessment',
            name='dhb_large_data_loss',
            field=models.CharField(choices=[('N', 'None'), ('I', 'Inconvenience'), ('D', 'Disruption'), ('P', 'Personal Injury'), ('S', 'Significant economic loss'), ('H', 'Human life endangered')], default='N', help_text='The effect of someone accidentally or malciously altering a LARGE amount of our data stored in the cloud service.', max_length=1),
        ),
        migrations.AddField(
            model_name='ictriskassessment',
            name='dhb_perm_loss',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='We have a plan we can put into effect if the cloud service loses our data permanently.', max_length=1),
        ),
        migrations.AddField(
            model_name='ictriskassessment',
            name='dhb_small_data_loss',
            field=models.CharField(choices=[('N', 'None'), ('I', 'Inconvenience'), ('D', 'Disruption'), ('P', 'Personal Injury'), ('S', 'Significant economic loss'), ('H', 'Human life endangered')], default='N', help_text='The effect of someone accidentally or malciously altering a SMALL amount of our data stored in the cloud service.', max_length=1),
        ),
    ]
