# Generated by Django 2.0.2 on 2018-07-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_auto_20180703_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTVendorAssessment',
            fields=[
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assessment.Application')),
                ('host_country', models.CharField(help_text='What country or countries is the service hosted in?', max_length=120)),
                ('host_service', models.CharField(help_text='Name any 3rd party suppliers used by the vendor to supply this service e.g. Microsoft Azure, Amazon Web Services.', max_length=120)),
                ('host_deploy', models.CharField(choices=[('M', 'Install an app on a mobile device'), ('P', 'Install an app on a PC or Citrix Terminal'), ('B', 'Build a server'), ('D', 'Install a modality'), ('H', 'The DHB does not have to do anything')], default='B', help_text='The service requires the customer to do the following work', max_length=1)),
                ('devices', models.CharField(choices=[('M', 'Mobile device'), ('P', 'PC'), ('C', 'Citrix terminal'), ('M', 'Modality')], default='P', help_text='Users access the service using the following technology', max_length=1)),
                ('encrypt_transmit', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The data is encrypted when it is being transmitted to the cloud service', max_length=1)),
                ('encrypt_stored', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The customer’s data is encrypted inside the cloud service data store', max_length=1)),
                ('anonimised', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The data is de-identified BEFORE  it is sent to the cloud service', max_length=1)),
                ('back_up', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor backs up the data stored in the cloud service', max_length=1)),
                ('extract', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor provides a means for the customer to download a copy of the  data stored  the cloud service', max_length=1)),
                ('restore', models.CharField(choices=[('H', 'Hours'), ('D', 'Days'), ('M', 'Months'), ('N', 'Does not')], default='U', help_text='The vendor undertakes to re-instate the service in the event of an outage in', max_length=1)),
                ('log_admin', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor logs sys admin access to  the  data stored in the cloud service', max_length=1)),
                ('log_access', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor logs end user access to  the data stored in the cloud service', max_length=1)),
                ('shares_data', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor allows 3rd parties to access the data stored in the cloud service', max_length=1)),
                ('notify_breach', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor will tell the customer if there has been a security or privacy  incident concerning the data stored in the cloud service', max_length=1)),
                ('patches', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor regularly applies  security patches to applications, devices, servers and hypervisors  ', max_length=1)),
                ('testing', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor undertakes regular  security testing / certification', max_length=1)),
                ('advise_legal_issues', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor will tell the customer if there has been a Court Order concerning the data stored in the cloud service', max_length=1)),
                ('ownership', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor’s terms of service give the vendor ownership rights over the data stored in the cloud service', max_length=1)),
                ('penalty_breach', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor will pay compensation if the customer suffers a loss as a result of a privacy or security breach of data stored in the cloud service', max_length=1)),
                ('penalty_outage', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor will  pay compensation if the  customer suffer a loss as a result of the cloud service being unavailable for any length of time', max_length=1)),
                ('report_outages', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor provides a means for the customer to complain in the event of a privacy breach or service disruption', max_length=1)),
                ('backgroud_checks', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='The vendor’s HR procedures include background vetting of employees and contractors', max_length=1)),
            ],
        ),
    ]
