# Generated by Django 2.0.2 on 2018-07-03 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_ictvendorassessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='owner_decision',
            new_name='clinical_decision',
        ),
        migrations.AddField(
            model_name='application',
            name='clinical_comments',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='dhb_breach_plan',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='8. We have a plan we can put into effect if we learn that there has been a privacy or security breach concerning our data stored in the cloud service.', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='dhb_disrupt_plan',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='9. We have a plan we can put into effect if the cloud service is disrupted for an extended period.', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='dhb_downtime_before_critical',
            field=models.CharField(choices=[('H', 'Hours'), ('D', 'Days'), ('M', 'Months'), ('I', 'Indefinitely')], default='H', help_text='4. We can be without this app before our service can no longer function properly. Specify the time interval.', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='dhb_large_data_loss',
            field=models.CharField(choices=[('N', 'None'), ('I', 'Inconvenience'), ('D', 'Disruption'), ('P', 'Personal Injury'), ('S', 'Significant economic loss'), ('H', 'Human life endangered')], default='N', help_text='7. The effect of someone accidentally or malciously altering a LARGE amount of our data stored in the cloud service.', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='dhb_log_data_changes',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='5. We will be able to notice if someone accidentally or maliously alters our data stored in the cloud service.', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='dhb_perm_loss',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='10. We have a plan we can put into effect if the cloud service loses our data permanently.', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='dhb_record_volume',
            field=models.CharField(choices=[('TENS', '10s'), ('HUNDREDS', '100s'), ('THOUSANDS', '1,000s'), ('TENTHOUSANDS', '10,000s'), ('HUNDREDTHOUSANDS', '100,000s')], default='TENS', help_text='3. Provide an estimate of the number of records we expect to store in the application on an annual basis.', max_length=15),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='dhb_small_data_loss',
            field=models.CharField(choices=[('N', 'None'), ('I', 'Inconvenience'), ('D', 'Disruption'), ('P', 'Personal Injury'), ('S', 'Significant economic loss'), ('H', 'Human life endangered')], default='N', help_text='6. The effect of someone accidentally or malciously altering a SMALL amount of our data stored in the cloud service.', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='privacypolicy_URL',
            field=models.URLField(help_text='2. Please copy and paste the apps privacy policy from the vendors website. Make sure you get the privacy policy for the version of the app you want.'),
        ),
        migrations.AlterField(
            model_name='ictriskassessment',
            name='termsconditions_URL',
            field=models.URLField(help_text='1. Please copy and paste the apps terms and conditions from the vendors website. Make sure you get the T&Cs for the version of the app you want.'),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='advise_legal_issues',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='17. The vendor will tell the customer if there has been a Court Order concerning the data stored in the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='anonimised',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='7. The data is de-identified BEFORE  it is sent to the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='back_up',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='8. The vendor backs up the data stored in the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='backgroud_checks',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='22. The vendor’s HR procedures include background vetting of employees and contractors', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='devices',
            field=models.CharField(choices=[('M', 'Mobile device'), ('P', 'PC'), ('C', 'Citrix terminal'), ('M', 'Modality')], default='P', help_text='4. Users access the service using the following technology', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='encrypt_stored',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='6. The customer’s data is encrypted inside the cloud service data store', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='encrypt_transmit',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='5. The data is encrypted when it is being transmitted to the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='extract',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='9. The vendor provides a means for the customer to download a copy of the  data stored  the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='host_country',
            field=models.CharField(help_text='1. What country or countries is the service hosted in?', max_length=120),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='host_deploy',
            field=models.CharField(choices=[('M', 'Install an app on a mobile device'), ('P', 'Install an app on a PC or Citrix Terminal'), ('B', 'Build a server'), ('D', 'Install a modality'), ('H', 'The DHB does not have to do anything')], default='B', help_text='3. The service requires the customer to do the following work', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='host_service',
            field=models.CharField(help_text='2. Name any 3rd party suppliers used by the vendor to supply this service e.g. Microsoft Azure, Amazon Web Services.', max_length=120),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='log_access',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='12. The vendor logs end user access to  the data stored in the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='log_admin',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='11. The vendor logs sys admin access to  the  data stored in the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='notify_breach',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='14. The vendor will tell the customer if there has been a security or privacy  incident concerning the data stored in the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='ownership',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='18. The vendor’s terms of service give the vendor ownership rights over the data stored in the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='patches',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='15. The vendor regularly applies  security patches to applications, devices, servers and hypervisors  ', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='penalty_breach',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='19. The vendor will pay compensation if the customer suffers a loss as a result of a privacy or security breach of data stored in the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='penalty_outage',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='20. The vendor will  pay compensation if the  customer suffer a loss as a result of the cloud service being unavailable for any length of time', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='report_outages',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='21. The vendor provides a means for the customer to complain in the event of a privacy breach or service disruption', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='restore',
            field=models.CharField(choices=[('H', 'Hours'), ('D', 'Days'), ('M', 'Months'), ('N', 'Does not')], default='U', help_text='10. The vendor undertakes to re-instate the service in the event of an outage in', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='shares_data',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='13. The vendor allows 3rd parties to access the data stored in the cloud service', max_length=1),
        ),
        migrations.AlterField(
            model_name='ictvendorassessment',
            name='testing',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], default='U', help_text='16. The vendor undertakes regular  security testing / certification', max_length=1),
        ),
    ]
