# Generated by Django 2.0.2 on 2018-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20180704_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='clinical_decision',
            field=models.CharField(choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='privacy_decision',
            field=models.CharField(choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='security_decision',
            field=models.CharField(choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], default='N', max_length=1),
        ),
    ]
