# Generated by Django 2.0.2 on 2018-07-07 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0016_auto_20180707_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalApplication',
            fields=[
                ('name', models.CharField(db_index=True, max_length=254)),
                ('website', models.URLField()),
                ('purpose', models.CharField(max_length=254)),
                ('cost', models.CharField(max_length=254)),
                ('cost_type', models.CharField(choices=[('1', 'One time payment'), ('M', 'Monthly'), ('Y', 'Annually')], default='Y', max_length=1, verbose_name='Renewal')),
                ('application_type', models.CharField(choices=[('C', 'Cloud'), ('M', 'Mobile'), ('D', 'Desktop'), ('T', 'Tablet'), ('H', 'Hybrid')], default='C', max_length=1, verbose_name='Type')),
                ('assess_status', models.CharField(choices=[('N', 'New'), ('A', 'Assessing'), ('R', 'Rejected'), ('P', 'Approved')], default='N', max_length=1, verbose_name='Status')),
                ('security_decision', models.CharField(choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], default='N', max_length=1)),
                ('security_comments', models.CharField(blank=True, max_length=254, null=True)),
                ('privacy_decision', models.CharField(choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], default='N', max_length=1)),
                ('privacy_comments', models.CharField(blank=True, max_length=254, null=True)),
                ('clinical_decision', models.CharField(choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], default='N', max_length=1)),
                ('clinical_comments', models.CharField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business_owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical application',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInformationClassification',
            fields=[
                ('medical_in_confidence', models.BooleanField(default=False, help_text='Personal health information')),
                ('staff_in_confidence', models.BooleanField(default=False, help_text='Identifiable employee and practitioner information that is not intended for the public domain')),
                ('commercial_in_confidence', models.BooleanField(default=False, help_text='Commercially sensitive information that needs protection from unauthorised access')),
                ('statistical_unclassified', models.BooleanField(default=False, help_text='Statistical or financial information that is non–identifiable')),
                ('unclassified', models.BooleanField(default=False, help_text='All other information')),
                ('special_handling_sensitive_patient', models.BooleanField(default=False, help_text='Sensitive patient information (eg VIP’s)')),
                ('special_handling_sensitive_disease', models.BooleanField(default=False, help_text='Sensitive categories of disease (eg Mental Health)')),
                ('special_handling_sensitive_abuse', models.BooleanField(default=False, help_text='Sensitive subjects (violence and abuse; pandemics)')),
                ('special_handling_sensitive_other', models.CharField(blank=True, help_text='Other', max_length=200, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('app', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assessment.Application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical information classification',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
