# Generated by Django 2.0.2 on 2018-07-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_historicalapplication_historicalinformationclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='DHB_accredited_for',
            field=models.CharField(choices=[('C', 'CCDHB'), ('H', 'HVDHB'), ('W', 'WrDHB')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='DHB_accredited_for',
            field=models.CharField(choices=[('C', 'CCDHB'), ('H', 'HVDHB'), ('W', 'WrDHB')], default='C', max_length=1),
        ),
    ]
