# Generated by Django 2.0.2 on 2018-07-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_auto_20180707_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='DHB_accredited_for',
            field=models.CharField(choices=[('C', 'CCDHB'), ('H', 'HVDHB'), ('W', 'WrDHB')], default='C', max_length=1, verbose_name='DHB(s)'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='DHB_accredited_for',
            field=models.CharField(choices=[('C', 'CCDHB'), ('H', 'HVDHB'), ('W', 'WrDHB')], default='C', max_length=1, verbose_name='DHB(s)'),
        ),
    ]
