# Generated by Django 2.0.2 on 2018-07-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_auto_20180708_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='DHB_accredited_for',
            field=models.CharField(blank=True, choices=[('C', 'CCDHB'), ('H', 'HVDHB'), ('W', 'WrDHB')], max_length=60, null=True, verbose_name='DHB(s)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('C', 'Cloud'), ('M', 'Mobile'), ('D', 'Desktop'), ('T', 'Tablet'), ('H', 'Hybrid')], default='C', max_length=60, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='DHB_accredited_for',
            field=models.CharField(blank=True, choices=[('C', 'CCDHB'), ('H', 'HVDHB'), ('W', 'WrDHB')], max_length=60, null=True, verbose_name='DHB(s)'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='application_type',
            field=models.CharField(choices=[('C', 'Cloud'), ('M', 'Mobile'), ('D', 'Desktop'), ('T', 'Tablet'), ('H', 'Hybrid')], default='C', max_length=60, verbose_name='Type'),
        ),
    ]
