# Generated by Django 2.0.2 on 2018-07-07 17:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('assessment', '0020_auto_20180708_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='DHB_accredited_for',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='DHB_accredited_for',
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
