# Generated by Django 2.0.2 on 2018-07-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_auto_20180708_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='icon_html',
            field=models.CharField(default='icon_html', max_length=200),
            preserve_default=False,
        ),
    ]
