# Generated by Django 2.0.2 on 2018-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_auto_20180708_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.ManyToManyField(to='assessment.ApplicationType'),
        ),
    ]
