# Generated by Django 2.0.2 on 2018-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_auto_20180708_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ictvendorassessment',
            name='devices',
        ),
        migrations.AddField(
            model_name='ictvendorassessment',
            name='devices',
            field=models.ManyToManyField(help_text='4. Users access the service using the following technology', to='assessment.TechDelivery'),
        ),
        migrations.RemoveField(
            model_name='ictvendorassessment',
            name='host_deploy',
        ),
        migrations.AddField(
            model_name='ictvendorassessment',
            name='host_deploy',
            field=models.ManyToManyField(help_text='3. The service requires the customer to do the following work', to='assessment.TechInstall'),
        ),
    ]
