# Generated by Django 2.0.2 on 2018-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0026_auto_20180708_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='clinical_decision',
            field=models.CharField(blank=True, choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='privacy_decision',
            field=models.CharField(blank=True, choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='security_decision',
            field=models.CharField(blank=True, choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='clinical_decision',
            field=models.CharField(blank=True, choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='privacy_decision',
            field=models.CharField(blank=True, choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='security_decision',
            field=models.CharField(blank=True, choices=[('N', 'No / Negligible Risk'), ('L', 'Low impact Risk'), ('H', 'High Impact Risk'), ('E', 'Extreme Risk')], max_length=1, null=True),
        ),
    ]
