# Generated by Django 2.0.2 on 2018-07-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0027_auto_20180709_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATmeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IPSGmeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyAssessment',
            fields=[
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assessment.Application')),
                ('pia_upload', models.FileField(upload_to='', verbose_name='Upload completed Privacy Assessment')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='attachments',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
