# Generated by Django 2.0.2 on 2018-07-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0028_auto_20180709_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CATmeetingdDecisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, choices=[('A', 'Approve'), ('R', 'Reject'), ('E', 'IPSG'), ('N', 'Noted')], max_length=1, null=True, verbose_name='CAT decision:')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='assessment.Application')),
            ],
        ),
        migrations.AddField(
            model_name='catmeeting',
            name='absentees',
            field=models.ManyToManyField(related_name='absentees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catmeeting',
            name='attendees',
            field=models.ManyToManyField(related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catmeeting',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location:'),
        ),
        migrations.AddField(
            model_name='catmeeting',
            name='meeting_minutes',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attach meeting minutes:'),
        ),
        migrations.AddField(
            model_name='catmeeting',
            name='meeting_time_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time:'),
        ),
        migrations.AddField(
            model_name='catmeetingddecisions',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catmeeting', to='assessment.CATmeeting'),
        ),
    ]
