# Generated by Django 2.0.2 on 2018-07-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0029_auto_20180709_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CATmeetingdDecisions',
            new_name='CATmeetingDecisions',
        ),
    ]
