# Generated by Django 2.0.2 on 2018-07-10 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_auto_20180711_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_time_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 10, 14, 45, 32, 715722, tzinfo=utc), verbose_name='Date & time:'),
        ),
    ]
