# Generated by Django 2.0.2 on 2018-07-10 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_auto_20180711_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_time_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & time:'),
        ),
    ]
