# Generated by Django 2.0.2 on 2018-07-10 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0033_auto_20180711_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_time_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date & time:'),
        ),
    ]
