# Generated by Django 2.0.2 on 2018-07-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0035_auto_20180711_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catmeetingdecisions',
            name='app',
        ),
        migrations.RemoveField(
            model_name='catmeetingdecisions',
            name='meeting',
        ),
        migrations.AddField(
            model_name='application',
            name='CATmeeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.CATmeeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='business_owner_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='escalate_to_IPSG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='noted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catmeeting',
            name='comments',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='CATmeeting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assessment.CATmeeting'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='business_owner_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='escalate_to_IPSG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='noted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CATmeetingDecisions',
        ),
    ]
