# Generated by Django 2.0.2 on 2018-07-10 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0036_auto_20180711_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='CATmeeting',
            new_name='CATmeetingID',
        ),
        migrations.RenameField(
            model_name='historicalapplication',
            old_name='CATmeeting',
            new_name='CATmeetingID',
        ),
        migrations.AddField(
            model_name='application',
            name='business_owner_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Submit Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='business_owner_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Submit Date'),
            preserve_default=False,
        ),
    ]
