# Generated by Django 2.0.2 on 2018-07-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0037_auto_20180711_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='CATmeetingID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.CATmeeting'),
        ),
    ]
