# Generated by Django 2.0.2 on 2018-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0038_auto_20180711_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='business_owner_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submit Date'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='business_owner_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submit Date'),
        ),
    ]
