# Generated by Django 2.0.2 on 2018-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0039_auto_20180711_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacyassessment',
            name='disclaimer',
            field=models.BooleanField(default=False),
        ),
    ]
