# Generated by Django 2.0.2 on 2018-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0041_remove_privacyassessment_pia_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacyassessment',
            name='pia_upload',
            field=models.FileField(default='null', upload_to='', verbose_name='Upload completed Privacy Assessment'),
            preserve_default=False,
        ),
    ]
