# Generated by Django 2.0.2 on 2018-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0042_privacyassessment_pia_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacyassessment',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='privacyassessment',
            name='pia_upload',
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='collection',
            field=models.BooleanField(default=False, help_text='Example: Collecting information about individuals’ location', verbose_name='A new collection of personal information'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='desc',
            field=models.CharField(blank=True, help_text='Describe your existing systems and the main changes that are proposed. Describe the purpose of the change, including any projected benefits to your organisation or to the individuals affected. Identify the main stakeholders or entities involved, and their role in the project.', max_length=255, null=True, verbose_name='Brief description of the project'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='disclosure',
            field=models.BooleanField(default=False, help_text='Example: Sharing information with other parties in a new way', verbose_name='A new use or disclosure of personal information that is already held'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='info_handling',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', help_text='Amount of personal information that will be handled.', max_length=1, verbose_name='Level of information handling'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='interaction',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', help_text='Number of other organisations involved.', max_length=1, verbose_name='Interaction with others'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='monitoring',
            field=models.BooleanField(default=False, help_text='Example: Installing a new CCTV system', verbose_name='Surveillance, tracking or monitoring of movements, behaviour or communications'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='new_collect',
            field=models.BooleanField(default=False, help_text='Example: Collecting information online rather than on paper forms', verbose_name='A new way of collecting personal information'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='new_id',
            field=models.BooleanField(default=False, help_text='Example: A unique identifier, a biometric, or an online identity system', verbose_name='Establishing a new way of identifying individuals'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='new_sensitive',
            field=models.BooleanField(default=False, help_text='Example: Moving health or financial records to a new database', verbose_name='A change to how sensitive information is managed'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='new_store',
            field=models.BooleanField(default=False, help_text='Example: Storing information in the cloud', verbose_name='A change in the way personal information is stored or secured'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='offshore',
            field=models.BooleanField(default=False, help_text='Example: Outsourcing the payroll function or storing information in the cloud', verbose_name='Transferring personal information offshore or using a third-party contractor'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='personal_info',
            field=models.CharField(blank=True, help_text='A description of the personal information that will be collected, used and/or disclosed; the source of the information; and the purpose of the information for your project.', max_length=255, null=True, verbose_name='Personal information that the project will involve'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='policy',
            field=models.BooleanField(default=False, help_text='Example: Archiving documents into a facility from which they can’t be easily retrieved', verbose_name='A change in policy that results in people having less access to information that you hold about them'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='premises',
            field=models.BooleanField(default=False, help_text='Example: Changing the location of the reception desk, meeting rooms  where people may discuss personal details', verbose_name='Changes to your premises that will involve private spaces where clients or customers may disclose their personal information '),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='public_impact',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', help_text='Impact on clients and the wider public. Concerns over aspects of project; or potential for negative media.', max_length=1, verbose_name='Public impact'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='regulatory',
            field=models.BooleanField(default=False, help_text='Example: Adding a new medical condition to the requirements of a pilot’s license', verbose_name='New regulatory requirements that could lead to compliance action against individuals on the basis of information about them '),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='risk_register',
            field=models.BooleanField(default=False, help_text='Example: Practices or activities listed on your office’s privacy risk register or health and safety register', verbose_name='Any practice or activity that is listed on a risk register kept by your organisation'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='sensitivity',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', help_text='Amount of sensitive information that will be handled.', max_length=1, verbose_name='Sensitivity of the information'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='sharing',
            field=models.BooleanField(default=False, help_text='Example: Combining information with other information held on public registers, or sharing information to enable organisations to provide services jointly', verbose_name='Sharing or matching personal information held by different organisations or currently held in different datasets'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='significance',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', help_text='Magnitude of change.', max_length=1, verbose_name='Significance of the changes'),
        ),
        migrations.AddField(
            model_name='privacyassessment',
            name='substantial_change',
            field=models.BooleanField(default=False, help_text='Example: New legislation or policy that makes it compulsory to collect or disclose information', verbose_name='A substantial change to an existing policy, process or system that involves personal information'),
        ),
    ]
