# Generated by Django 2.0.2 on 2018-07-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0043_auto_20180717_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='CATmeetingID',
            new_name='CATmeetingCode',
        ),
        migrations.RenameField(
            model_name='historicalapplication',
            old_name='CATmeetingID',
            new_name='CATmeetingCode',
        ),
        migrations.RemoveField(
            model_name='catmeeting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='catmeeting',
            name='meeting_minutes',
        ),
        migrations.AddField(
            model_name='catmeeting',
            name='meeting_code',
            field=models.CharField(default='CAT<built-in method today of type object at 0x0000000051C03340>156', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='assess_status',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Submitted'), ('A', 'Assessing'), ('R', 'Rejected'), ('P', 'Approved')], default='N', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='assess_status',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Submitted'), ('A', 'Assessing'), ('R', 'Rejected'), ('P', 'Approved')], default='N', max_length=1, verbose_name='Status'),
        ),
    ]
