# Generated by Django 2.0.2 on 2018-07-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0047_auto_20180717_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_code',
            field=models.CharField(default='CAT-2018-07-17-ID-230', max_length=30, primary_key=True, serialize=False),
        ),
    ]
