# Generated by Django 2.0.2 on 2018-07-16 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0048_auto_20180717_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_code',
            field=models.CharField(default='CAT-2018-07-17-ID-477', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_date',
            field=models.DateField(default=datetime.date(2018, 7, 17), verbose_name='Date:'),
        ),
    ]
