# Generated by Django 2.0.2 on 2018-07-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0049_auto_20180717_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmeeting',
            name='meeting_code',
            field=models.CharField(default='CAT-2018-07-17-ID-127', max_length=30, primary_key=True, serialize=False),
        ),
    ]
